### ISSUE TITLE
Don't ask for WP test path after using the wpppb-init

### ISSUE THREAD

**Issue by ScreamingDev** [JDGrimes/wpppb#22]
```
Please enter the full path to the WordPress tests directory (ex. /path/to/wordpress/tests/phpunit/):
```

Well, the init script just created this so why is it asking?

**Comment by JDGrimes** [comment]
It is asking for the path to the tests directory in a WordPress core development checkout, not the current project. It is expecting you to already have a development version of WordPress installed locally. (Like using VVV, for example.)
