### ISSUE TITLE
sed not working while setting DB prefix

### ISSUE THREAD

**Issue by ScreamingDev** [JDGrimes/wpppb#24]
Seems like you are in macOS 

```
Copying tests/phpunit/test-uninstall.php...
Please enter the prefix that your plugin uses in the database (ex. my_plugin):
wp_
sed: can't read s/myplugin/wp_/: No such file or directory
```

Please use sed with every parameter (note the `-e`):

```
sed -i '' -e "s/myplugin/$prefix/" tests/phpunit/test-uninstall.php
```

Guessing like `sed -i 's/foo/bar/' baz.php` differs form OS to OS too much.

**Comment by JDGrimes** [comment]
> Seems like you are in macOS

Guilty as charged. 😄 

Would you like to submit a PR?
